### ISSUE TITLE
Missing word in sentence

### ISSUE THREAD

**Issue by barryp** [Frencil/galaxy_of_nuclides#17]
In galaxy_of_nuclides/assets/js/questions/what_is_a_nuclide.js there is a sentence:

```
The number of in an atom determines what element it is (and therefore its chemistry).
```

Seems like it's missing the word "protons" (or "electrons"?)  between "number of" and "in an atom"

**Comment by Frencil** [comment]
Thanks for catching that! Fix pushed to master.
